"""Offline scoring — turn recorded sessions into research-grounded numbers.

    >>> This *is* implemented, unlike the live categorizers in features.py. Those
    >>> stay stubs because *which quality to sonify in real time* is an open thesis
    >>> question. Here we do post-hoc analysis of finished recordings, where the
    >>> established EMG metrics are well defined and worth computing verbatim.

RECORDING MODEL (important — the scorer's whole shape follows from it)
--------------------------------------------------------------------------
Each subject directory holds:

    recordings/<subject>/
        <stamp>_amp/            <- MVC test: one sustained maximal contraction
        <stamp>_overheadfast/   <- one REP of the "overheadfast" movement
        <stamp>_overheadfast/   <- another rep of the same movement
        ... (~6 reps per movement category) ...
        <stamp>_point/          <- reps of another category ...

So **one folder = one rep**, and the reps of a movement are *grouped by category*
(the folder-name suffix after the timestamp). The unit of analysis is therefore
the **category** (a group of ~6 rep files), not the individual file. We report:

    scores.csv   one row per (subject, category): the reps aggregated
    reps.csv     one row per individual rep file (drill-down)

The `amp` recording is the subject's **MVC reference**, not a scored category. Its
maximum drives %MVC normalisation. To avoid a lone sensor-shift spike defining
100%, the reference is a *robust* max — a high percentile (99th) of the amp
contraction's envelope (`robust_max`), which discards the top ~1% of samples where
a shift artefact would land while still reflecting the true attainable peak. Rep
envelopes are then clipped only well above MVC (`SPIKE_TRIM_FACTOR` × MVC) so that
gross shift artefacts are removed but normal dynamic overshoot (a fast rep can beat
an isometric hold) is preserved — %MVC is therefore not capped at 100 (`score_rep`).

THE FEATURE SET (llm_director_extension.md §10.3)
--------------------------------------------------------------------------
Five features, derived top-down from De Luca (1997)'s three sEMG domains — activation
timing (D1), force/amplitude (D2), spectral/fatigue (D3) — in CEDE terminology. The
derivation happens *before any gesture is named*, so the instrument is not fitted to
the stimulus it will measure. This replaced an earlier set that had been generated by
an LLM reasoning from the target movement and then miscited; that set is gone.

    T1  t1_rer_pct_mvc_s          D1  rate of EMG rise: max(dE/dt) on the rise
    T2  t2_offset_rate_pct_mvc_s  D1  offset rate: max(-dE/dt) on the fall
    T3  t3_burst_frac             D1  burst duration / cued movement window
    A1  a1_peak_pct_mvc           D2  peak envelope, %MVC
    S1  s1_mdf_hz                 D3  median frequency (secondary — see below)

All amplitude-bearing features are normalised to the subject's session MVC, so they
are comparable across subjects without per-person anatomical calibration.

REP BOUNDARIES — detected against the quiet pre-cue baseline
--------------------------------------------------------------------------
The participant was prompted to move on the third beep, stamped into session.json as
`movement_onset_s` by `mark_movement()`. That cue anchors the search but is NOT the
boundary: reaction time lags it by a median of ~0.55 s (and up to ~1.4 s), which for a
short gesture would swamp the measurement. `rep_window()` detects the actual burst —
the active run containing the envelope peak — by thresholding smoothed TKEO energy at
`mean + k·SD` of the pre-cue baseline.

The threshold references the *quiet baseline*, not the recording's own peak. That is
the crucial difference from the retired `segment_reps`: a percentile-of-this-file
threshold creeps up into a slow contraction and clips its gradual rise/fall, reporting
a sharper onset than really happened. A baseline-referenced threshold does not.

Weak slow contractions still sit low over baseline, so `rep_window()` walks a leniency
ladder (k = 3, 2, 1.5) and takes the first burst spanning >= MIN_BOX_FRAC of the cued
window; failing that it falls back to [cue, end] and sets `box_fallback`. The ladder
stops at 1.5 because below it the baseline itself starts crossing.

T1, T2 and A1 are max-statistics, so they are nearly boundary-insensitive (any
adequate box contains the steepest slope and the peak). T3 is the boundary-sensitive
one — it is §10.3's literal (t_offset - t_onset) / movement-window, so it depends
entirely on a real detected offset, and is left None on fallback reps.

Supporting signal-quality metrics, unchanged and never mixed into the five:

    snr         baseline_noise, snr_db — rest-vs-active signal-to-noise. The
                research makes a signal-quality gate a hard requirement so the
                system never adapts to electrode artefact (lit. review §9, Arg 4).
    mains       mains_residual — fraction of power left at mains + harmonics after
                host notching. The dry PCB pads pick up a lot of 50/60 Hz hum.
    contact     contact_frac — fraction of samples the wear/contact flag reported OK.

Multichannel metrics (co-contraction [R23]-[R26], recruitment specificity) need a
second electrode and are deliberately left out (deferred in semester_plan.md too).

KNOWN DEVIATIONS — report these, do not "fix" them
--------------------------------------------------------------------------
1. The rig samples at 500 Hz and band-passes to 200 Hz; §10.3.1 asks for >=1000 Hz
   and 20-450 Hz. At 500 Hz Nyquist is 250 Hz, so that band is unreachable, and all
   recordings already exist. S1 is the casualty — the spectrum is truncated well
   below where MDF would otherwise sit, so S1 stays SECONDARY and out of the primary
   endpoint (§10.3 also excludes it as a performer-state, not movement, property).
2. T2 and T3 are right-censored wherever `truncated` is set (the detected burst runs
   into the last sample): the recording ended while the muscle was still active, so
   the offset was never observed. Concentrated in the `point` gesture. Always report
   the truncated rate beside T2/T3, and note T3 is additionally None on fallback reps.
3. The timing and amplitude features are not independent, as measured on this data
   (739 scored reps): T1 x A1 r = 0.85, T1 x T2 r = 0.86, T1 x T3 r = 0.02.
   - T1/A1 is the expected speed-force conflation of the "as fast/strong as you can"
     instruction; MVC normalisation does not separate them.
   - T1/T2 is the one to watch. T2 is supposed to be the *non-telegraphed* feature
     (no instruction says what happens after the endpoint), so it carries a lot of
     weight in showing a model did more than match words. At r = 0.86 it largely
     tracks T1, which "fast"/"slow" telegraphs directly — so T2 may inherit that
     telegraphing rather than testing against it. Report the correlation beside any
     claim resting on T2.
   - T3 is close to independent of T1, so it is the timing feature actually adding a
     separate dimension.

--------------------------------------------------------------------------
HOW TO ADD A METRIC
--------------------------------------------------------------------------
Per-rep metrics live in `score_rep()` — add a key to the returned dict and to
REP_METRIC_COLUMNS; it will flow into reps.csv and, via the median in
`aggregate_category()`, into scores.csv automatically. The composite `quality_score`
is a transparent, reconfigurable signal-quality gate over the aggregated metrics
(QualityWeights / composite_quality) — the five features are reported raw, never
baked into one verdict.

This module is leakage-controlled (§10.8): freeze it before any LLM prediction
exists, and do not tune thresholds afterward.
"""

from __future__ import annotations

import csv
import json
import math
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
from scipy import signal

from .config import Config
from .streaming import process_offline, tkeo

# --------------------------------------------------------------------------- #
#  Columns  (internal keys are unit-less; labels below add units for the CSV)
# --------------------------------------------------------------------------- #
SCORE_COLUMN = "quality_score"

# The five §10.3 features, in domain order. These are the study's endpoint; S1 is
# elicited and reported but held out of the primary (see the module docstring).
FEATURE_COLUMNS: Tuple[str, ...] = (
    "t1_rer_pct_mvc_s",
    "t2_offset_rate_pct_mvc_s",
    "t3_burst_frac",
    "a1_peak_pct_mvc",
    "s1_mdf_hz",
)
# Per-rep extraction flags. Not measurements — they say how far to trust one.
# box_k is the threshold (in SDs) that the burst detector succeeded at; it is a
# level, not a rate, so it aggregates by median while the 0/1 flags aggregate by mean.
FLAG_COLUMNS: Tuple[str, ...] = ("truncated", "cue_missing", "box_fallback", "box_k")
# Signal-quality gate. Describes the recording, never the movement.
QUALITY_COLUMNS: Tuple[str, ...] = (
    "baseline_noise", "snr_db", "mains_residual", "contact_frac",
)

# Per-rep metric keys, produced by score_rep(). Category rows carry the median of
# each of these — keep the two in sync.
REP_METRIC_COLUMNS: Tuple[str, ...] = (
    *FEATURE_COLUMNS, *FLAG_COLUMNS, *QUALITY_COLUMNS,
)

REP_COLUMNS: Tuple[str, ...] = (
    "subject", "category", "rep", "started",
    "duration_s", "n_samples", "sample_rate", "mains_hz",
    *REP_METRIC_COLUMNS,
)
CATEGORY_COLUMNS: Tuple[str, ...] = (
    "subject", "category", "n_reps", "mvc_reference",
    *REP_METRIC_COLUMNS, SCORE_COLUMN,
)

# Human-readable CSV headers with units. The rig is an uncalibrated 10-bit ADC
# (adc_max=1023), so there is no µV conversion — every amplitude-bearing feature is
# expressed as %MVC instead, which is what makes it comparable across subjects.
# Columns not listed fall back to their key.
COLUMN_LABELS: Dict[str, str] = {
    "duration_s": "duration (s)",
    "sample_rate": "sample_rate (Hz)",
    "mains_hz": "mains (Hz)",
    "mvc_reference": "MVC ref (counts)",
    "t1_rer_pct_mvc_s": "T1 rate of EMG rise (%MVC/s)",
    "t2_offset_rate_pct_mvc_s": "T2 offset rate (%MVC/s)",
    "t3_burst_frac": "T3 burst fraction (0-1)",
    "a1_peak_pct_mvc": "A1 peak (%MVC)",
    "s1_mdf_hz": "S1 median freq (Hz)",
    "truncated": "truncated (frac)",
    "cue_missing": "cue_missing (frac)",
    "box_fallback": "box_fallback (frac)",
    "box_k": "box_k (SD)",
    "baseline_noise": "baseline_noise (counts)",
    "snr_db": "snr (dB)",
    "mains_residual": "mains_residual (frac)",
    "contact_frac": "contact (frac)",
    "quality_score": "quality_score (0-1)",
}

MVC_PERCENTILE = 99.0   # percentile of the amp contraction taken as 100% MVC
SPIKE_TRIM_FACTOR = 1.5  # clip rep envelopes above this × MVC (shift artefacts)
AMP_CATEGORY = "amp"    # the MVC-reference folder name (not a scored category)

# Burst detection thresholds the smoothed TKEO energy at baseline mean + k * SD
# (Hodges & Bui's k = 2-3 convention). SMOOTH_S is the moving-average width that turns
# instantaneous TKEO into a thresholdable activation envelope.
SMOOTH_S = 0.025
# Leniency ladder for rep_window(): try these thresholds (in SDs) hardest-first and
# accept the first burst spanning >= MIN_BOX_FRAC of the cued window. A weak, slow
# contraction sits low over the baseline, so the strict threshold clips it or misses
# it; relaxing recovers it. Bounded at 1.5 because below that the pre-cue baseline
# itself starts crossing (false activation rises 2% -> 12% from k=3 to k=1).
K_LADDER: Tuple[float, ...] = (3.0, 2.0, 1.5)
MIN_BOX_FRAC = 0.15
MERGE_GAP_S = 0.10      # bridge gaps shorter than this between active runs
# 0/1 flags aggregate by mean (-> a rate); box_k is a level and aggregates by median.
BINARY_FLAGS = ("truncated", "cue_missing", "box_fallback")
# Half-width of the window centred on the envelope peak used for S1. Short, because
# spectral estimates assume quasi-stationarity and dynamic movement violates it.
MDF_HALF_WINDOW_S = 0.125

_STAMP_RE = re.compile(r"^\d{4}-\d{2}-\d{2}_\d{6}_")

# Folder-name typos made during collection. The folder names are raw collected data
# and are not renamed on disk; they are reconciled here so the reps land in the cell
# they were actually recorded for.
CATEGORY_ALIASES: Dict[str, str] = {
    "kickfast": "kickbackfast",
    "kickslow": "kickbackslow",
}


def category_of(dataset_dir: Path) -> str:
    """Movement category = the folder name with its `YYYY-MM-DD_HHMMSS_` prefix
    stripped, so all reps of one movement share a category (`overheadfast`, ...).
    Known collection-time misspellings are mapped to the intended category."""
    name = Path(dataset_dir).name
    stripped = _STAMP_RE.sub("", name) or name
    return CATEGORY_ALIASES.get(stripped, stripped)


# --------------------------------------------------------------------------- #
#  Burst / rep segmentation
# --------------------------------------------------------------------------- #
def _runs(mask: np.ndarray) -> List[Tuple[int, int]]:
    """Half-open [start, end) index ranges of contiguous True in a bool mask."""
    if mask.size == 0:
        return []
    m = mask.astype(np.int8)
    edges = np.diff(np.concatenate(([0], m, [0])))
    starts = np.flatnonzero(edges == 1)
    ends = np.flatnonzero(edges == -1)
    return list(zip(starts.tolist(), ends.tolist()))


def _merge_runs(runs: List[Tuple[int, int]], merge_gap: int) -> List[Tuple[int, int]]:
    """Bridge [start, end) runs separated by <= `merge_gap` samples [R15]."""
    merged: List[Tuple[int, int]] = []
    for s, e in runs:
        if merged and s - merged[-1][1] <= merge_gap:
            # max(): a run nested inside the span it merges into must not shorten it
            merged[-1] = (merged[-1][0], max(e, merged[-1][1]))
        else:
            merged.append((s, e))
    return merged


def segment_reps(
    envelope: np.ndarray,
    fs: float,
    onset_frac: float = 0.20,
    min_rep_s: float = 0.12,
    merge_gap_s: float = 0.10,
) -> List[Tuple[int, int]]:
    """Amplitude-threshold onset detection over the envelope.

    A burst is a run where the envelope rises `onset_frac` of the way from its
    resting level (20th pct) to its peak (95th pct). Short runs are dropped and
    runs separated by < `merge_gap_s` are merged [R15]. Returns [start, end)
    sample ranges; empty when the signal is essentially flat.

    >>> MVC/amp FILE ONLY. The threshold is relative to *this recording's own*
    >>> percentile range, which fails on slow scored reps: when the burst fills much
    >>> of the file the 20th-pct "rest" creeps up into the contraction, raising the
    >>> threshold so the gradual rise crosses late and the box clamps around the
    >>> plateau — reading back a sharper onset/offset than really happened. Scored
    >>> reps use `rep_window()`, whose threshold comes from the quiet pre-cue
    >>> baseline instead. This function stays only because the amp file has no cue.
    """
    n = envelope.size
    if n == 0 or fs <= 0:
        return []
    rest = float(np.percentile(envelope, 20))
    peak = float(np.percentile(envelope, 95))
    span = peak - rest
    if span <= 1e-9:
        return []
    thr = rest + onset_frac * span

    reps = _runs(envelope > thr)
    if not reps:
        return []

    merged = _merge_runs(reps, int(round(merge_gap_s * fs)))
    min_len = max(1, int(round(min_rep_s * fs)))
    return [(s, e) for s, e in merged if e - s >= min_len]


def dominant_rep(envelope: np.ndarray, fs: float) -> Tuple[int, int]:
    """The single active burst of a one-rep file: the strongest run from
    `segment_reps` (by envelope peak). Falls back to the whole array when no burst
    is detected (e.g. a very short or flat recording)."""
    reps = segment_reps(envelope, fs)
    if not reps:
        return (0, envelope.size)
    return max(reps, key=lambda se: float(envelope[se[0]:se[1]].max())
               if se[1] > se[0] else 0.0)


TIME_NORM_LEN = 100     # samples in a time-normalised rep envelope profile


def rep_profile(seg: np.ndarray, n: int = TIME_NORM_LEN) -> Optional[np.ndarray]:
    """Resample a rep's envelope onto `n` points in [0,1] time so reps of different
    durations can be overlaid shape-for-shape.

    Presentational only — the viewer's overlay mode uses it. No §10.3 feature is
    derived from a time-normalised profile, because normalising away duration would
    discard exactly what T3 measures.
    """
    if seg.size < 2:
        return None
    xp = np.linspace(0.0, 1.0, seg.size)
    xq = np.linspace(0.0, 1.0, n)
    return np.interp(xq, xp, seg)


def _smooth_tkeo(tk: np.ndarray, fs: float, smooth_s: float = SMOOTH_S) -> np.ndarray:
    """Smoothed |TKEO| -> a thresholdable activation-energy envelope.

    TKEO output is *instantaneous* energy, dipping toward zero twice per carrier cycle
    even mid-burst, so thresholding it raw gives a shredded mask. A short moving
    average (`smooth_s`) turns it into the smooth envelope onset detection thresholds.
    """
    w = max(1, int(round(smooth_s * fs)))
    if w <= 1:
        return np.abs(tk)
    kern = np.ones(w, dtype=np.float64) / w
    return np.convolve(np.abs(tk), kern, mode="same")


def rep_window(ctx: "DatasetContext") -> Optional[Tuple[int, int, Optional[float], bool]]:
    """Detected burst boundaries for a scored rep: (start, end, k_used, fallback).

    Returns None when the recording has no movement cue (nothing anchors the search).

    The window is the active burst *containing the envelope peak*, found by
    thresholding the pre-cue-referenced activation energy. Search is confined to
    [cue, end]: the movement cannot precede the prompt, and excluding the pre-cue
    stretch keeps the detector out of the very baseline that sets its threshold.

    Leniency ladder: a weak, slow contraction sits low over the baseline, so the
    strict k=3 threshold clips or misses it. We try K_LADDER hardest-first and accept
    the first burst spanning >= MIN_BOX_FRAC of the cued window. If none qualifies we
    fall back to the whole cued window and flag it — better an honest "we could not
    localise this" than a box tuned down onto noise.
    """
    ci = ctx.cue_index()
    if ci is None:
        return None
    env, fs, n = ctx.envelope, ctx.fs, ctx.envelope.size
    win = n - ci
    if win < 2 or fs <= 0:
        return (ci, n, None, True)

    peak_i = ci + int(np.argmax(env[ci:]))
    energy = _smooth_tkeo(tkeo(ctx.filtered), fs)
    base = energy[:ci]
    merge_gap = int(round(MERGE_GAP_S * fs))
    best: Optional[Tuple[int, int]] = None

    if base.size >= 2:
        base_mean, base_sd = float(base.mean()), float(base.std())
        for k in K_LADDER:
            thr = base_mean + k * base_sd
            active = energy > thr
            active[:ci] = False                 # search only after the cue
            runs = _merge_runs(_runs(active), merge_gap)
            box = next(((s, e) for s, e in runs if s <= peak_i < e), None)
            if box is None:
                continue
            if best is None:
                best = box                      # remember the strictest box we found
            if (box[1] - box[0]) >= MIN_BOX_FRAC * win:
                return (box[0], box[1], k, False)

    if best is not None and (best[1] - best[0]) >= MIN_BOX_FRAC * win:
        return (best[0], best[1], K_LADDER[-1], False)
    return (ci, n, None, True)


def robust_max(envelope: np.ndarray, fs: float,
               pct: float = MVC_PERCENTILE) -> Optional[float]:
    """MVC reference: a high percentile of the amp contraction's envelope.

    Taken over the amp file's dominant burst (its actual contraction, not the rest
    before/after). The `pct`th percentile (default 99th) discards the top ~1% of
    samples — where a lone sensor-shift spike would sit — while still reflecting the
    true attainable peak, so one artefact can't define 100% MVC. A moving-average
    "sustained max" was tried first but sat well below real rep peaks and made every
    %MVC saturate; a percentile is on the same instantaneous scale as a rep's peak.
    """
    if envelope.size == 0 or fs <= 0:
        return None
    s, e = dominant_rep(envelope, fs)
    seg = envelope[s:e] if e > s else envelope
    if seg.size == 0:
        seg = envelope
    return float(np.percentile(seg, pct))


# --------------------------------------------------------------------------- #
#  Spectral helpers (shared by mains + spectral metrics)
# --------------------------------------------------------------------------- #
def _mains_residual(f: np.ndarray, fs: float, mains_hz: float) -> Optional[float]:
    if f.size < 64 or fs <= 0:
        return None
    nperseg = int(min(f.size, max(64, fs)))
    freqs, psd = signal.welch(f, fs=fs, nperseg=nperseg)
    total = float(np.sum(psd))
    if total <= 0:
        return None
    bw = 1.5
    band = np.zeros_like(freqs, dtype=bool)
    k = 1
    while mains_hz * k < 0.99 * (fs / 2.0):
        band |= (freqs >= mains_hz * k - bw) & (freqs <= mains_hz * k + bw)
        k += 1
    return float(np.sum(psd[band]) / total)


def _median_freq(x: np.ndarray, fs: float) -> Optional[float]:
    if x.size < 64 or fs <= 0:
        return None
    nperseg = int(min(x.size, max(64, fs)))
    freqs, psd = signal.welch(x, fs=fs, nperseg=nperseg)
    cumulative = np.cumsum(psd)
    if cumulative[-1] <= 0:
        return None
    return float(np.interp(cumulative[-1] / 2.0, cumulative, freqs))


# --------------------------------------------------------------------------- #
#  Loading one rep file
# --------------------------------------------------------------------------- #
@dataclass
class DatasetContext:
    """Everything loaded from one recording folder (one rep, or the amp file)."""
    subject: str
    dataset: str
    path: Path
    meta: dict
    cfg: Config
    fs: float
    t: np.ndarray
    raw: np.ndarray
    filtered: np.ndarray
    envelope: np.ndarray
    contact: np.ndarray            # float array, NaN where the flag was absent
    _rep: Optional[Tuple[int, int]] = field(default=None, repr=False)

    def rep(self) -> Tuple[int, int]:
        """[start, end) of this file's single dominant rep (cached).

        Amplitude-detected. Used for the MVC/amp file, which has no movement cue;
        scored reps use `rep_window()` instead.
        """
        if self._rep is None:
            self._rep = dominant_rep(self.envelope, self.fs)
        return self._rep

    def cue_index(self) -> Optional[int]:
        """Sample index of the movement cue (the third beep), or None if unstamped.

        `movement_onset_s` is seconds from the first recorded sample, written by
        Recorder.mark_movement(). Rejected when it falls outside the recording or
        leaves no usable pre-cue baseline. Anchors `rep_window()`'s burst search.
        """
        cue_s = self.meta.get("movement_onset_s")
        if cue_s is None or self.fs <= 0:
            return None
        i = int(round(float(cue_s) * self.fs))
        if i < 2 or i >= self.envelope.size:
            return None
        return i

    @property
    def category(self) -> str:
        return category_of(self.path)


def _read_signal_csv(path: Path) -> Dict[str, np.ndarray]:
    """Read signal.csv into named float columns; blank cells become NaN."""
    with open(path, "r", newline="", encoding="utf-8") as fh:
        reader = csv.reader(fh)
        header = next(reader, None)
        if not header:
            raise ValueError(f"empty signal file: {path}")
        cols: Dict[str, List[float]] = {h: [] for h in header}
        for line in reader:
            if not line:
                continue
            for h, cell in zip(header, line):
                cell = cell.strip()
                cols[h].append(float(cell) if cell else math.nan)
    return {h: np.asarray(v, dtype=np.float64) for h, v in cols.items()}


def load_dataset(dataset_dir: Path, recordings_root: Path,
                 stored: bool = False,
                 mains_hz: Optional[float] = None) -> DatasetContext:
    """Load one recording folder into a DatasetContext.

    By default `filtered`/`envelope` are **re-derived from raw with the zero-phase
    offline chain**, discarding the stored columns. Two reasons, both required by
    §10.3.1/§10.8: the stored columns came from the causal live chain, whose group
    delay biases timing measurements; and re-deriving guarantees every rep in the
    study passed through one frozen pipeline rather than whatever the live config
    happened to be that session.

    `stored=True` uses the recorded columns instead — what the subject actually heard
    through the sonifier. That is a playback/inspection mode, not a scoring mode.
    """
    dataset_dir = Path(dataset_dir)
    meta_path = dataset_dir / "session.json"
    meta: dict = {}
    if meta_path.exists():
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
    cfg = Config.from_dict(meta.get("config", {})) if meta.get("config") else Config()
    if mains_hz is not None:
        cfg.mains_hz = mains_hz

    data = _read_signal_csv(dataset_dir / "signal.csv")
    if "raw" not in data:
        raise ValueError(f"{dataset_dir/'signal.csv'} has no 'raw' column")
    raw = data["raw"]
    fs = float(cfg.sample_rate)
    t = data.get("t")
    if t is None or t.size != raw.size:
        t = np.arange(raw.size, dtype=np.float64) / fs

    have_filtered = "filtered" in data and not np.all(np.isnan(data["filtered"]))
    have_envelope = "envelope" in data and not np.all(np.isnan(data["envelope"]))
    if stored and have_filtered and have_envelope:
        filtered = data["filtered"]
        envelope = data["envelope"]
    else:
        filtered, envelope = process_offline(cfg, raw)

    contact = data.get("contact_ok", np.full(raw.size, math.nan))

    try:
        rel = dataset_dir.resolve().relative_to(recordings_root.resolve())
        subject = rel.parts[0] if len(rel.parts) > 1 else ""
    except ValueError:
        subject = dataset_dir.parent.name

    return DatasetContext(
        subject=subject,
        dataset=dataset_dir.name,
        path=dataset_dir,
        meta=meta,
        cfg=cfg,
        fs=fs,
        t=t,
        raw=raw,
        filtered=np.asarray(filtered, dtype=np.float64),
        envelope=np.asarray(envelope, dtype=np.float64),
        contact=np.asarray(contact, dtype=np.float64),
    )


# --------------------------------------------------------------------------- #
#  Discovery: recordings -> subjects -> categories -> rep folders
# --------------------------------------------------------------------------- #
def find_datasets(recordings_root: Path) -> List[Path]:
    """Every folder under recordings_root that contains a signal.csv, sorted."""
    root = Path(recordings_root)
    if not root.exists():
        return []
    return sorted(p.parent for p in root.rglob("signal.csv"))


@dataclass
class SubjectGroup:
    """One test subject: their MVC (amp) folder and their movement categories."""
    subject: str
    amp_dir: Optional[Path]
    categories: Dict[str, List[Path]]   # category -> rep folders (sorted), no amp


def find_subjects(recordings_root: Path) -> List[SubjectGroup]:
    """Group every rep folder under recordings_root by subject then category.

    The subject is the folder directly under the recordings root; rep folders that
    sit in the root itself (old flat layout) are grouped under "(ungrouped)". The
    `amp` category is pulled aside as the subject's MVC reference.
    """
    root = Path(recordings_root)
    root_res = root.resolve()
    by_subject: Dict[str, List[Path]] = {}
    for d in find_datasets(root):
        parent = d.parent
        subject = "(ungrouped)" if parent.resolve() == root_res else parent.name
        by_subject.setdefault(subject, []).append(d)

    groups: List[SubjectGroup] = []
    for subject in sorted(by_subject):
        amp_dir: Optional[Path] = None
        categories: Dict[str, List[Path]] = {}
        for d in sorted(by_subject[subject]):
            cat = category_of(d)
            if cat == AMP_CATEGORY:
                if amp_dir is None:
                    amp_dir = d  # first amp folder is the MVC reference
                continue
            categories.setdefault(cat, []).append(d)
        groups.append(SubjectGroup(subject, amp_dir, categories))
    return groups


def subject_mvc(amp_dir: Optional[Path], recordings_root: Path,
                stored: bool = False, mains_hz: Optional[float] = None) -> Optional[float]:
    """Robust MVC reference (counts) for a subject from their amp recording, or
    None when there is no amp folder / it can't be loaded.

    Must go through the same chain as the reps it normalises — an MVC measured on a
    differently-filtered signal is not a valid denominator.
    """
    if amp_dir is None:
        return None
    try:
        ctx = load_dataset(amp_dir, recordings_root, stored=stored, mains_hz=mains_hz)
    except Exception:
        return None
    return robust_max(ctx.envelope, ctx.fs)


# --------------------------------------------------------------------------- #
#  Scoring one rep, then aggregating a category
# --------------------------------------------------------------------------- #
def score_rep(ctx: DatasetContext,
              mvc: Optional[float]) -> Dict[str, Optional[float]]:
    """The five §10.3 features plus quality metrics for one rep file.

    The scored window is the detected burst from `rep_window()` — the active run
    containing the envelope peak, its onset found relative to the quiet pre-cue
    baseline so a slow rise is not clipped. When the burst cannot be localised the
    window falls back to [cue, end] and `box_fallback` is set; T3 is then None, since
    a whole-window box makes it meaningless.

    When an MVC is given, the envelope is clipped above SPIKE_TRIM_FACTOR × MVC first,
    so a sensor-shift spike cannot define either the peak (A1) or the slope (T1/T2) —
    but normal dynamic overshoot is preserved, which is why %MVC is not capped at 100.

    Every feature is None rather than 0 when it cannot be computed; a missing
    measurement must never be averaged in as if it were a small one.
    """
    env = ctx.envelope
    filt = ctx.filtered
    fs = ctx.fs
    row: Dict[str, Optional[float]] = {k: None for k in REP_METRIC_COLUMNS}

    cue = ctx.cue_index()
    row["cue_missing"] = 0.0 if cue is not None else 1.0

    window = rep_window(ctx)
    if window is not None:
        s, e, k_used, fallback = window
        row["box_fallback"] = float(fallback)
        row["box_k"] = k_used
    else:
        # No cue: fall back to amplitude detection so an unstamped recording still
        # yields quality metrics, but the features stay None — they are only
        # meaningful against the protocol's own window.
        s, e = ctx.rep()
        fallback = True

    rep_env = env[s:e]
    rep_filt = filt[s:e]
    rest_filt = filt[:s]

    ceil = mvc * SPIKE_TRIM_FACTOR if (mvc and mvc > 0) else None
    rep_env_c = np.minimum(rep_env, ceil) if ceil else rep_env

    # ---- signal quality (always computed) ---------------------------------
    base = float(np.sqrt(np.mean(rest_filt ** 2))) if rest_filt.size else None
    row["baseline_noise"] = base
    if base and base > 0 and rep_filt.size:
        rms_act = float(np.sqrt(np.mean(rep_filt ** 2)))
        row["snr_db"] = 20.0 * math.log10(rms_act / base)
    row["mains_residual"] = _mains_residual(filt, fs, ctx.cfg.mains_hz)

    c = ctx.contact
    valid = c[~np.isnan(c)] if c.size else c
    row["contact_frac"] = float(np.mean(valid)) if valid.size else None

    if window is None or rep_env_c.size < 2 or fs <= 0:
        return row

    # Truncated = the detected burst runs into the last sample: the recording stopped
    # while the muscle was still active, so the offset (and T2/T3) were never seen.
    row["truncated"] = float(e >= env.size)

    peak_i = int(np.argmax(rep_env_c))
    peak = float(rep_env_c[peak_i])

    # ---- A1: peak amplitude, %MVC ----------------------------------------
    if mvc and mvc > 0:
        row["a1_peak_pct_mvc"] = peak / mvc * 100.0

    # ---- T1 / T2: envelope slope on the rise and the fall ------------------
    # One derivative of the box, split at the peak. The rising phase runs onset ->
    # peak and the falling phase peak -> offset, so each max() picks the steepest
    # excursion in its own direction. Boundary-insensitive (a max over any adequate
    # box), which is why they held up even under the cue-window definition.
    if mvc and mvc > 0:
        d = np.gradient(rep_env_c, 1.0 / fs)
        rise, fall = d[:peak_i + 1], d[peak_i:]
        if rise.size:
            row["t1_rer_pct_mvc_s"] = float(rise.max()) / mvc * 100.0
        # A peak at the very end leaves no falling phase: max(-dE/dt) would be
        # negative (a still-rising envelope), not a rate of decay. Report nothing —
        # the deactivation was never observed. `truncated` marks these.
        if fall.size >= 2:
            decay = float((-fall).max())
            if decay > 0:
                row["t2_offset_rate_pct_mvc_s"] = decay / mvc * 100.0

    # ---- T3: burst duration as a fraction of the cued movement window ------
    # §10.3's (t_offset - t_onset) / movement duration, with the burst boundaries from
    # rep_window() and the movement window measured from the cue (so variable pre-cue
    # dead time stays out of the denominator). Undefined on a fallback box, which
    # spans the whole window and would force T3 = 1.
    if not fallback and cue is not None and e > cue:
        row["t3_burst_frac"] = (e - s) / (env.size - cue)

    # ---- S1: median frequency over the burst plateau -----------------------
    # On the band-passed signal — rectifying and smoothing to an envelope destroys
    # the spectrum. Short window centred on the peak, per the stationarity caveat.
    half = max(1, int(round(MDF_HALF_WINDOW_S * fs)))
    a = max(0, s + peak_i - half)
    b = min(filt.size, s + peak_i + half)
    plateau = filt[a:b]
    row["s1_mdf_hz"] = _median_freq(plateau if plateau.size >= 64 else rep_filt, fs)

    return row


def _finite(values) -> List[float]:
    return [float(v) for v in values
            if v is not None and not (isinstance(v, float) and math.isnan(v))]


def _nanmedian(values) -> Optional[float]:
    xs = _finite(values)
    return float(np.median(xs)) if xs else None


def _nanmean(values) -> Optional[float]:
    xs = _finite(values)
    return float(np.mean(xs)) if xs else None


def rep_row(ctx: DatasetContext, subject: str, category: str,
            mvc: Optional[float]) -> Dict[str, object]:
    """One reps.csv row: identity + the five features + flags + quality."""
    row: Dict[str, object] = {
        "subject": subject,
        "category": category,
        "rep": ctx.dataset,
        "started": ctx.meta.get("started", ""),
        "duration_s": ctx.meta.get("duration_s", round(ctx.raw.size / ctx.fs, 3)),
        "n_samples": ctx.raw.size,
        "sample_rate": int(ctx.fs),
        "mains_hz": ctx.cfg.mains_hz,
    }
    row.update(score_rep(ctx, mvc))
    return row


def aggregate_category(subject: str, category: str, mvc: Optional[float],
                       rep_rows: List[Dict[str, object]],
                       weights: Optional["QualityWeights"] = None) -> Dict[str, object]:
    """Collapse a category's rep rows into one scores.csv row.

    Features and quality metrics are aggregated by MEDIAN, per §10.4 step 1 — one
    fumbled rep should not move the cell. The 0/1 flags (BINARY_FLAGS) aggregate by
    MEAN, giving the *rate* (fraction truncated / fallback), which is what reporting
    needs. box_k is a threshold level, not a rate, so it stays on the median.
    """
    cat: Dict[str, object] = {
        "subject": subject,
        "category": category,
        "n_reps": len(rep_rows),
        "mvc_reference": round(mvc, 4) if mvc else None,
    }
    for col in REP_METRIC_COLUMNS:
        values = [r.get(col) for r in rep_rows]
        cat[col] = _nanmean(values) if col in BINARY_FLAGS else _nanmedian(values)
    cat[SCORE_COLUMN] = composite_quality(cat, weights)
    return cat


# --------------------------------------------------------------------------- #
#  Composite signal-quality gate  (transparent + reconfigurable)
# --------------------------------------------------------------------------- #
@dataclass
class QualityWeights:
    """Knobs for composite_quality(). Defaults are a documented heuristic, not a
    law — the research fixes only that a quality gate must *exist* (exclude noisy
    reps), not its exact form. Tune freely for your rig."""
    snr_floor_db: float = 3.0
    snr_good_db: float = 20.0
    mains_tol: float = 0.20
    w_snr: float = 0.6
    w_mains: float = 0.4


def _clamp01(x: float) -> float:
    return 0.0 if x < 0.0 else 1.0 if x > 1.0 else x


def composite_quality(row: Dict[str, object],
                      w: Optional[QualityWeights] = None) -> Optional[float]:
    """0..1 signal-integrity score: is this (aggregated) recording clean enough to
    trust? Blends SNR + mains sub-scores (reweighted to whatever is present) then
    gates on contact fraction. None when no quality evidence exists. Excludes the
    motor-learning metrics — those describe the movement, not signal usability."""
    w = w or QualityWeights()
    parts: List[Tuple[float, float]] = []

    snr = row.get("snr_db")
    if snr is not None and w.snr_good_db > w.snr_floor_db:
        parts.append((w.w_snr, _clamp01(
            (float(snr) - w.snr_floor_db) / (w.snr_good_db - w.snr_floor_db))))

    mains = row.get("mains_residual")
    if mains is not None and w.mains_tol > 0:
        parts.append((w.w_mains, _clamp01(1.0 - float(mains) / w.mains_tol)))

    if not parts:
        return None
    total_w = sum(wt for wt, _ in parts)
    base = sum(wt * sub for wt, sub in parts) / total_w if total_w > 0 else 0.0

    contact = row.get("contact_frac")
    gate = float(contact) if contact is not None else 1.0
    return _clamp01(base * gate)


# --------------------------------------------------------------------------- #
#  Scoring everything
# --------------------------------------------------------------------------- #
def score_all(recordings_root: Path, stored: bool = False,
              mains_hz: Optional[float] = None,
              weights: Optional[QualityWeights] = None,
              ) -> Tuple[List[Dict[str, object]], List[Dict[str, object]],
                         List[Tuple[Path, str]]]:
    """Score every subject/category under recordings_root.

    Returns (category_rows, rep_rows, failures): one aggregated row per
    (subject, category), one row per rep file, and (path, error) for reps that
    could not be loaded. The amp folders are used as MVC references, not scored.
    """
    category_rows: List[Dict[str, object]] = []
    rep_rows: List[Dict[str, object]] = []
    failures: List[Tuple[Path, str]] = []
    root = Path(recordings_root)

    for group in find_subjects(root):
        mvc = subject_mvc(group.amp_dir, root, stored=stored, mains_hz=mains_hz)
        for category in sorted(group.categories):
            rows: List[Dict[str, object]] = []
            for d in group.categories[category]:
                try:
                    ctx = load_dataset(d, root, stored=stored, mains_hz=mains_hz)
                except Exception as exc:
                    failures.append((d, f"{type(exc).__name__}: {exc}"))
                    continue
                rows.append(rep_row(ctx, group.subject, category, mvc))
            if not rows:
                continue
            rep_rows.extend(rows)
            category_rows.append(
                aggregate_category(group.subject, category, mvc, rows, weights))

    category_rows.sort(key=lambda r: (str(r["subject"]), str(r["category"])))
    rep_rows.sort(key=lambda r: (str(r["subject"]), str(r["category"]), str(r["rep"])))
    return category_rows, rep_rows, failures


# --------------------------------------------------------------------------- #
#  CSV output
# --------------------------------------------------------------------------- #
def _fmt(value: object) -> str:
    """Format a cell for CSV: blanks for None/NaN, ~4 significant figures."""
    if value is None:
        return ""
    if isinstance(value, float):
        if math.isnan(value):
            return ""
        return f"{value:.4g}"
    return str(value)


def header_labels(columns: Tuple[str, ...]) -> List[str]:
    """Header row for `columns`: each labelled with its unit where it has one."""
    return [COLUMN_LABELS.get(c, c) for c in columns]


def write_csv(rows: List[Dict[str, object]], out_path: Path,
              columns: Tuple[str, ...]) -> Path:
    """Write rows to a clean CSV in the given column order, with unit-labelled
    headers (data stays keyed by the bare column names)."""
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(header_labels(columns))
        for row in rows:
            writer.writerow([_fmt(row.get(col)) for col in columns])
    return out_path
